### ISSUE TITLE
Missing SoundFileIO.c

### ISSUE THREAD

**Issue by corporealfunk** [tomerbe/SoundHack#1]
Hi, noticed while tracing through some code that the repository seems to be missing the SoundFile.c or SoundFileIO.c as referenced here in the headers: https://github.com/tomerbe/SoundHack/blob/071c725b2a9a37cb70a39d1d2c3129883c79aa2e/SoundFile/SoundFile.h#L150

Wondering if you could commit that? Thanks.

**Comment by tomerbe** [comment]
it's up now - GitHub and apple cloud services not playing well together.

**Comment by corporealfunk** [comment]
thanks!
